# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"G\n\x0fImageAndDataset\x12\x19\n\x05image\x18\x01 \x01(\x0b\x32\n.ImageData\x12\x19\n\x07\x64\x61taset\x18\x02 \x01(\x0b\x32\x08.Dataset\":\n\nBytesImage\x12\r\n\x05\x62ytes\x18\x01 \x03(\r\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\"\x19\n\tImageData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\"5\n\x07\x44\x61taset\x12\x1a\n\x06images\x18\x01 \x03(\x0b\x32\n.ImageData\x12\x0e\n\x06owners\x18\x02 \x03(\t\"H\n\nImageOwner\x12\x16\n\x0eis_in_database\x18\x01 \x01(\x08\x12\r\n\x05owner\x18\x02 \x01(\t\x12\x13\n\x0bprobability\x18\x03 \x01(\x02\x32u\n\x16ImageProcessingService\x12)\n\x0cGetImageData\x12\x0b.BytesImage\x1a\n.ImageData\"\x00\x12\x30\n\rGetImageOwner\x12\x10.ImageAndDataset\x1a\x0b.ImageOwner\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEANDDATASET']._serialized_start=17
  _globals['_IMAGEANDDATASET']._serialized_end=88
  _globals['_BYTESIMAGE']._serialized_start=90
  _globals['_BYTESIMAGE']._serialized_end=148
  _globals['_IMAGEDATA']._serialized_start=150
  _globals['_IMAGEDATA']._serialized_end=175
  _globals['_DATASET']._serialized_start=177
  _globals['_DATASET']._serialized_end=230
  _globals['_IMAGEOWNER']._serialized_start=232
  _globals['_IMAGEOWNER']._serialized_end=304
  _globals['_IMAGEPROCESSINGSERVICE']._serialized_start=306
  _globals['_IMAGEPROCESSINGSERVICE']._serialized_end=423
# @@protoc_insertion_point(module_scope)
