# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ImageProcessingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetImageData = channel.unary_unary(
                '/ImageProcessingService/GetImageData',
                request_serializer=service__pb2.BytesImage.SerializeToString,
                response_deserializer=service__pb2.ImageData.FromString,
                _registered_method=True)
        self.GetImageOwner = channel.unary_unary(
                '/ImageProcessingService/GetImageOwner',
                request_serializer=service__pb2.ImageAndDataset.SerializeToString,
                response_deserializer=service__pb2.ImageOwner.FromString,
                _registered_method=True)


class ImageProcessingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetImageData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImageOwner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageProcessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetImageData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImageData,
                    request_deserializer=service__pb2.BytesImage.FromString,
                    response_serializer=service__pb2.ImageData.SerializeToString,
            ),
            'GetImageOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImageOwner,
                    request_deserializer=service__pb2.ImageAndDataset.FromString,
                    response_serializer=service__pb2.ImageOwner.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageProcessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageProcessingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetImageData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImageProcessingService/GetImageData',
            service__pb2.BytesImage.SerializeToString,
            service__pb2.ImageData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImageOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImageProcessingService/GetImageOwner',
            service__pb2.ImageAndDataset.SerializeToString,
            service__pb2.ImageOwner.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
